openapi: 3.0.3
info:
  title:  Rest API
  description: All Item Rest API End Points
  version: V-2024-04
servers:
  - url: http://localhost:8080
tags:
  - name: Note
paths:
  /note:
    post:
      tags:
        - Note
      summary: Create a new note
      description: Add a new note in the app
      operationId: createNote
      requestBody:
        description: note data required to create a new note
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNoteDTO'
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: string
                format: UUID

components:
  schemas:
    CreateNoteDTO:
      type: object
      properties:
        title:
          type: string
          description: title of the note
        content:
          type: string
          description: content of the note